---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - ${APPDATA_PATH}/plex/config:/config
      - ${MOVIES_PATH}:/data/Movies
      - ${TV_PATH}:/data/TV
      - /tmp:/transcode
    hostname: ubuntu1
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: always
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PUID=${PUID}
      - PGID=${PGID}
      - ALLOWED_NETWORKS="10.0.0.0/8"
      - ADVERTISE_IP=${ADVERTISE_IP}
      - TZ=${TZ}

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    volumes:
      - ${APPDATA_PATH}/openvpn-client:/vpn
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    dns: 8.8.8.8

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
      - deluge
      - nginxdeluge
    volumes:
      - /homem/mandreko/sonarr:/config
      - ${TV_PATH}:/tv
      - ${APPDATA_PATH}/downloads:/downloads
    ports:
      - 8989:8989
    links:
      - nzbget
      - nginxdeluge
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - nzbget
      - deluge
      - nginxdeluge
    volumes:
      - ${APPDATA_PATH}/radarr:/config
      - ${APPDATA_PATH}/downloads:/downloads
      - ${MOVIES_PATH}:/movies
    links:
      - nzbget
      - nginxdeluge
    ports:
      - 7878:7878
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    depends_on:
      - vpn
    network_mode: host
    network_mode: "service:vpn"
    volumes:
      - ${APPDATA_PATH}/deluge:/config
      - ${APPDATA_PATH}/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  nginxdeluge:
    image: dperson/nginx
    container_name: nginxdeluge
    depends_on:
      - deluge
      - vpn
    links:
      - vpn:deluge
    ports:
      - 8112:80
    command: -w "http://deluge:8112;/"

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - ${APPDATA_PATH}/nzbget:/config
      - ${APPDATA_PATH}/downloads:/downloads
    ports:
      - 6789:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

