---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /home/mandreko/plex/config:/config
      - /mnt:/data
      - /tmp:/transcode
    hostname: ubuntu1
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}
      - ALLOWED_NETWORKS="10.0.0.0/8"
      - ADVERTISE_IP="http://10.0.50.200:32400"
      - TZ="America/Indianapolis"

  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    volumes:
      - /home/mandreko/openvpn-client:/vpn
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    dns: 8.8.8.8

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
      - deluge
      - nginxdeluge
    volumes:
      - /homem/mandreko/sonarr:/config
      - /mnt/TV:/tv
      - /home/mandreko/downloads:/downloads
    ports:
      - 8989:8989
    links:
      - nzbget
      - nginxdeluge
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - nzbget
      - deluge
      - nginxdeluge
    volumes:
      - /home/mandreko/radarr:/config
      - /home/mandreko/downloads:/downloads
      - /mnt/Movies:/movies
    links:
      - nzbget
      - nginxdeluge
    ports:
      - 7878:7878
    environment:
      - TZ="America/Indianapolis"
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    depends_on:
      - vpn
    network_mode: host
    network_mode: "service:vpn"
    volumes:
      - /home/mandreko/deluge:/config
      - /home/mandreko/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}

  nginxdeluge:
    image: dperson/nginx
    container_name: nginxdeluge
    depends_on:
      - deluge
      - vpn
    links:
      - vpn:deluge
    ports:
      - 8112:80
    command: -w "http://deluge:8112;/"

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /home/mandreko/nzbget:/config
      - /home/mandreko/downloads:/downloads
    ports:
      - 6789:6789
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}




